<?php
$cfgShop = array (
  'install' => true,
  'shop_close' => 0,
  's_or_items' => 0,
  's_by_items' => 'id',
  'r_op_items' => 8,
  'r_op_hstry' => 10,
  'r_op_cart' => 10,
  'r_op_prmlst' => 20,
  'currency' => 'майн.',
  'currency2' => 'руб.',
  'shop_id' => 'myid',
  'secret_key' => 'mykey',
  'cur_multip' => 1,
  'tbl_cont' => 'shop_content',
  'tbl_cat' => 'shop_categories',
  'tbl_cart' => 'shop_cart',
  'tbl_hist' => 'shop_history',
  'tbl_keys' => 'shop_keys',
  'tbl_trans' => 'shop_transactions',
  'tbl_trlog' => 'shop_translog',
  'tbl_temp' => 'shop_temp',
  'style' => 'shop/',
  'use_intkas' => 1,
  'use_vaucher' => 1,
  'use_permlist' => 1,
  'use_gift' => 1,
  'use_over64' => 1,
);
?>